language: python
python:
- '3.4'
- '3.5'
before_script:
- sudo python setup.py build --force install

#install:
#- pip install -U pip wheel
#- pip install -r requirements.txt

script:
- python tests.py
