language: python
python:
- '3.4'
- '3.5'
compiler:
  - clang
  - gcc
before_install:
- sudo apt-get install python3-dev -y
before_script:
- sudo python setup.py build --force install

#install:
#- pip install -U pip wheel
#- pip install -r requirements.txt

script:
- python tests.py
